version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    entrypoint: ./entrypoints/docker-entrypoint.sh
    environment:
      RAILS_ENV: development
    networks:
      custom_net:
        ipv4_address: 172.20.0.4

  database:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      custom_net:
        ipv4_address: 172.20.0.3

  redis:
    image: redis:7.2.4
    networks:
      custom_net:
        ipv4_address: 172.20.0.2

volumes:
  gem_cache:
  db_data:
  node_modules:

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
